from mmse15project.model.DBConnectionSQLite import *
from mmse15project.model.AccountDBInterface import *
from mmse15project.model.Account import *
from mmse15project.model.ClientDBInterface import *
from mmse15project.model.Client import *
from mmse15project.model.Request import  *
from mmse15project.model.RequestDBInterface import *
from mmse15project.model.FinancialRequest import *
from mmse15project.model.FinancialRequestDBInterface import *
from mmse15project.model.RecruitmentRequestDBInterface import *
from mmse15project.model.RecruitmentRequest import *
from mmse15project.model.RequestDetails import *
from mmse15project.model.RequestDetailsDBInterface import *
from mmse15project.model.DiscountDBInterface import *
from mmse15project.model.TaskDBInterface               import *
from mmse15project.model.ClientMeetingDBInterface      import *
from mmse15project.model.ScheduleDBInterface           import *
from mmse15project.model.GenericMethods import tuple_without
import os.path
def GenericMethodsTest():
    tuple_test = (1,2,3)
    tuple_test = tuple_without(tuple_test,0)
    assert(tuple_test[0]==2)
    assert(len(tuple_test)==2)
    assert(equal_tuples(tuple_test,(3,2))==False)
    assert(equal_tuples(tuple_test,(3))==False)
    assert(equal_tuples(tuple_test,(2,3))==True)
    assert(equal_tuples(tuple_test,(1,1,1,1))==False)
    print("Passed GenericMethods test")

def DBTest():
    db = DBConnectionSQLite('test_connection.test')
    assert(os.path.isfile('test_connection.test')==True)
    assert(db.isConnectionOk() == True)
    assert(db.getConnectionName() == 'test_connection.test')
    db.executeDoQuery('DROP TABLE IF EXISTS test')
    db.executeDoQuery('create TABLE test (id integer)')
    db.executeDoQuery('insert into test (id) values (1)')
    assert(db.getLastRow()==1)
    a=db.executeKnowQuery('select * from test')
    assert(len(a)==1)
    assert(a[0][0]==1)
    db.executeDoQuery('DROP TABLE IF EXISTS test')
    db.executeDoQuery('create TABLE test (id integer PRIMARY KEY AUTOINCREMENT,name text)')
    db.executeDoQuery('insert into test (name) values (?)',('test',))
    assert(db.getLastRow()==1)
    a=db.executeKnowQuery('select * from test')
    assert(len(a)==1)
    assert(a[0][0]==1)
    assert(a[0][1]=='test')
    print('Passed DBConnection test')

def AccountTest(db):
    account = Account('test','test','test',AccountType.InvalidType.value,AccountTeam.InvalidTeam.value,AccountQualification.InvalidQualification.value,'test','test')
    assert(account.name == 'test')
    assert(len(account.getAll()) ==8)
    assert(equal_tuples(account.getAll(), ('test','test','test',AccountType.InvalidType.value,AccountTeam.InvalidTeam.value,AccountQualification.InvalidQualification.value,'test','test')))
    account.setAll(('tes1t','tes2t','te3st',AccountType.Employee.value,AccountTeam.InvalidTeam.value,AccountQualification.Audio.value,'t4est','te5st'))
    assert(equal_tuples(account.getAll(), ('tes1t','tes2t','te3st',AccountType.Employee.value,AccountTeam.InvalidTeam.value,AccountQualification.Audio.value,'t4est','te5st')))
    assert (db.isConnectionOk() == 1)
    db.executeDoQuery("DROP TABLE IF EXISTS account")
    db.executeDoQuery(
        "CREATE TABLE  account (email text PRIMARY KEY, password text,name text,accountType INTEGER,accountTeam INTEGER,accountQualification INTEGER, department text,comment text)")
    db.executeDoQuery(
        "INSERT INTO account (email,password,name,accountType,accountTeam,accountQualification,department,comment) VALUES ('test@kth.se','password','Alessio',1,1,1,'management','')")
    DBAcc = AccountDBInterface(db)
    account = DBAcc.login('test@kth.se', 'password')
    assert (account.getPassword() == "password")
    assert (account.getEmail() == 'test@kth.se')
    assert (account.getName() == 'Alessio')
    assert (account.getAccountType() == 1)
    DBAcc.add(Account("ale@kth.se", "test", "ale", 1,1,0,'test',''))
    account = DBAcc.login('ale@kth.se', 'test')
    assert (account.getPassword() == "test")
    assert (account.getEmail() == 'ale@kth.se')
    assert (account.getName() == 'ale')
    assert (account.getAccountType() == 1)
    account.setName('bob')
    DBAcc.update(account)
    account=DBAcc.get(account)
    assert (account.getName() == 'bob')
    account = DBAcc.login("wrong","wrong")
    assert(account == False)
    account = DBAcc.getByEmail('test@kth.se')
    assert(account.email=='test@kth.se')
    a = DBAcc.getAll()
    assert(len(a)==2)
    assert(a[0].email == 'test@kth.se')
    print("Passed Account test")

def ClientTest(db):
    client = Client(1,'test','tess','test',100,'Genova','01/01/1990')
    assert(client.email == 'test')
    assert(len(client.getAll()) ==7)
    assert(equal_tuples(client.getAll(), (1,'test','tess','test',100,'Genova','01/01/1990')))
    client.setAll((12,'te2st','te1ss','tes2t',1200,'Gen2ova','03/01/1990'))
    assert(equal_tuples(client.getAll(), (12,'te2st','te1ss','tes2t',1200,'Gen2ova','03/01/1990')))

    assert (db.isConnectionOk() == 1)
    db.executeDoQuery("DROP TABLE IF EXISTS client")
    db.executeDoQuery(
        "CREATE TABLE  client (id INTEGER PRIMARY KEY AUTOINCREMENT, email text NOT NULL UNIQUE, name text  NOT NULL, address text NOT NULL ,postalCode integer,city    text NOT NULL ,birthdate text NOT NULL)")
    ClientDB = ClientDBInterface(db)
    client = Client(0,'alessior@kth.se','Alessio Russo','via la spezia 10/8', 16149, 'Genova','11/03/1991')
    client.id=ClientDB.add(client)
    assert(client.id != 0)
    client = ClientDB.get(client)
    assert(client.getName() == 'Alessio Russo')
    client.name ="Russo Alessio"
    ClientDB.update(client)
    client = ClientDB.get(client)
    assert(client.getName() == 'Russo Alessio')
    client = ClientDB.getByEmail('alessior@kth.se')
    assert(client.getName() == 'Russo Alessio')
    client = ClientDB.getByName('Alessio')
    assert(len(client)==1)
    client=client[0]
    assert(client.getName() == 'Russo Alessio')
    a = ClientDB.getAll()
    assert(len(a) ==1)
    assert(a[0].getName() == 'Russo Alessio')
    client =  ClientDB.getByID(1)
    assert(client.getName() == 'Russo Alessio')
    client = ClientDB.getByID(2)
    assert(client == False)
    print("Passed Client test")

def RequestTest(db):
    request = Request(1,1,'party','01/01/1000','10/10/2000',1000,100,'no',RequestStatus.Pending.value,'comments')
    assert(request.eventType == 'party')
    assert(len(request.getAll()) ==10)
    assert(equal_tuples(request.getAll(), (1,1,'party','01/01/1000','10/10/2000',1000,100,'no',RequestStatus.Pending.value,'comments')))
    request.setAll((12,12,'pa2rty','02/01/1000','12/10/2000',1003,3,'n1o',RequestStatus.Accepted1.value,'comm3ents'))
    assert(equal_tuples(request.getAll(), (12,12,'pa2rty','02/01/1000','12/10/2000',1003,3,'n1o',RequestStatus.Accepted1.value,'comm3ents')))

    assert (db.isConnectionOk() == 1)
    db.executeDoQuery("DROP TABLE IF EXISTS request")
    db.executeDoQuery(
        "CREATE TABLE IF NOT EXISTS request(id INTEGER PRIMARY KEY AUTOINCREMENT,clientID INTEGER,eventType text,startDate text,endDate   text,expectedParticipants integer,expectedBudget integer,preferences text,status integer,comment text,FOREIGN KEY(clientID) REFERENCES client(id))")
    reqDB = RequestDBInterface(db)
    request = Request(0,1,'Party','10/10/2015','10/10/2015',100,10000,'None',RequestStatus.Pending.value,'comment')
    request.id = reqDB.add(request)
    request = reqDB.getByID(request.id)
    assert(request.clientid == 1)
    ans = reqDB.getByClientID(1)
    assert(len(ans)==1)
    request= ans[0]
    assert(request.clientid == 1)
    request.expectedBudget=10
    reqDB.update(request)
    request = reqDB.get(request)[0]
    assert(request.expectedBudget == 10)
    request = reqDB.getByClientID(1)
    assert(len(request)==1)
    assert(request[0].expectedBudget==10)
    a = reqDB.getAll()
    assert(len(a)==1)
    assert(a[0].expectedBudget==10)
    a = reqDB.getByStatus(RequestStatus.Pending.value)
    assert(a[0].expectedBudget==10)
    print("Passed Request test")
def FinancialRequestTest(db):
    fr = FinancialRequest(1,'10/10/2015','dep1',1,1000,'test',FinancialRequestStatus.Pending.value)
    assert(fr.department == 'dep1')
    assert(len(fr.getAll()) ==7)
    assert(equal_tuples(fr.getAll(), (1,'10/10/2015','dep1',1,1000,'test',FinancialRequestStatus.Pending.value)))
    fr.setAll((12,'10/12/2015','dep31',31,10300,'te3st',FinancialRequestStatus.Approved.value))
    assert(equal_tuples(fr.getAll(), (12,'10/12/2015','dep31',31,10300,'te3st',FinancialRequestStatus.Approved.value)))
    assert (db.isConnectionOk() == 1)
    db.executeDoQuery("DROP TABLE IF EXISTS financialRequest")
    db.executeDoQuery(
        "CREATE TABLE IF NOT EXISTS financialRequest(id INTEGER PRIMARY KEY AUTOINCREMENT,date text,department text,requestID integer,amount integer,reason  text,status integer,FOREIGN KEY(requestID) REFERENCES request(id))")

    reqDB = FinancialRequestDBInterface(db)
    request = FinancialRequest(0,'10/10/2015','Administration',1,1000,'Test',FinancialRequestStatus.Pending.value)
    request.id=reqDB.add(request)
    assert(request.id != 0)
    request= reqDB.get(request)
    assert(request.amount == 1000)
    request.amount=2000
    reqDB.update(request)
    request = reqDB.get(request)
    assert(request.amount == 2000)
    a=reqDB.getAll()
    assert(len(a)==1)
    a=a[0]
    assert(a.amount == 2000)
    a=reqDB.getByRequestID(1)
    assert(len(a)==1)
    assert(a[0].amount == 2000)
    a = reqDB.getByStatus(1)
    assert(len(a)==1)
    a = reqDB.getByID(1)
    assert(a.amount == 2000)
    print("Passed FinancialRequest test")

def RecruitmentRequestTest(db):
    rr = RecruitmentRequest(1,RecruitmentType.invalidType.value,'01/01/1991','test','test',RecruitmentStatus.invalidType.value,'test')
    assert(rr.id== 1)
    assert(len(rr.getAll()) ==7)
    assert(equal_tuples(rr.getAll(), (1,RecruitmentType.invalidType.value,'01/01/1991','test','test',RecruitmentStatus.invalidType.value,'test')))
    rr.setAll((12,RecruitmentType.hire.value,'01/03/1991','te3st','t3est',RecruitmentStatus.completed.value,'tes3t'))
    assert(equal_tuples(rr.getAll(), (12,RecruitmentType.hire.value,'01/03/1991','te3st','t3est',RecruitmentStatus.completed.value,'tes3t')))
    assert (db.isConnectionOk() == 1)
    db.executeDoQuery("DROP TABLE IF EXISTS recruitmentRequest")
    db.executeDoQuery(
        "CREATE TABLE IF NOT EXISTS recruitmentRequest(id INTEGER PRIMARY KEY AUTOINCREMENT,type integer,date text,department text,title text,status integer,description text)")
    reqDB = RecruitmentRequestDBInterface(db)
    request = RecruitmentRequest(0,RecruitmentType.hire.value,'10/10/2015','Administration','Customer Service Operator',RecruitmentStatus.active.value,'none')
    request.id = reqDB.add(request)
    assert(request.id != 0)
    request=reqDB.get(request)
    assert(request.department=='Administration')
    request.department='HR'
    reqDB.update(request)
    request= reqDB.get(request)
    assert(request.department == 'HR')
    a=reqDB.getAll()
    assert(len(a)==1)
    assert(a[0].department=='HR')
    a = reqDB.getByID(2)
    assert(a==False)
    a = reqDB.getByStatus(RecruitmentStatus.active.value)
    assert(len(a)==1)
    print('Passed RecruitmentRequest test')

def RequestDetailsTest(db):
    rqd = RequestDetails(1,'test1','test','test','test','test','test','test')
    assert(rqd.id == 1)
    assert(len(rqd.getAll()) ==8)
    assert(equal_tuples(rqd.getAll(), (1,'test1','test','test','test','test','test','test')))
    rqd.setAll((12,'test12','test2','tes2t','tes2t','tes3t','te4st','tes5t'))
    assert(equal_tuples(rqd.getAll(), (12,'test12','test2','tes2t','tes2t','tes3t','te4st','tes5t')))
    assert (db.isConnectionOk() == 1)
    db.executeDoQuery("DROP TABLE IF EXISTS requestDetails")
    db.executeDoQuery(
        "CREATE TABLE IF NOT EXISTS requestDetails(id INTEGER PRIMARY KEY,detail1 text,detail2 text,detail3 text,detail4 text,detail5 text,detail6 text,needs text,FOREIGN KEY(id) REFERENCES request(id))")
    reqDB = RequestDetailsDBInterface(db)
    request = RequestDetails(1,'test','','','','','','')
    request.id = reqDB.add(request)
    assert(request.id != 0)
    request=reqDB.get(request)
    assert(request.detail1=='test')
    request.detail1='test2'
    reqDB.update(request)
    request= reqDB.get(request)
    assert(request.detail1 == 'test2')
    a=reqDB.getAll()
    assert(len(a)==1)
    assert(a[0].detail1=='test2')
    a = reqDB.getByID(1)
    assert(a.detail1=='test2')
    print('Passed RequestDetails test')


def DiscountTest(db):
    d = Discount(1,100,'comment','10/10/2015')
    assert(d.requestID == 1)
    assert(len(d.getAll()) ==4)
    assert(equal_tuples(d.getAll(),(1,100,'comment','10/10/2015')))
    d.setAll((12,1002,'comm2ent','13/10/2015'))
    assert(equal_tuples(d.getAll(), (12,1002,'comm2ent','13/10/2015')))

    assert (db.isConnectionOk() == 1)
    db.executeDoQuery("DROP TABLE IF EXISTS discount")
    db.executeDoQuery(
        "CREATE TABLE IF NOT EXISTS discount(requestID INTEGER,amount INTEGER,comment text,date text,FOREIGN KEY(requestID) references request(id))")
    reqDB = DiscountDBinterface(db)
    request = Discount(1,1000,'won the lottery','10/10/2015')
    reqDB.add(request)
    request = reqDB.get(request)
    assert(request.amount==1000)
    request.amount = 3000
    reqDB.update(request)
    request = reqDB.get(request)
    assert(request.amount==3000)
    req2 = Discount(1,2000,'won the lottery twice','10/10/2015')
    reqDB.add(req2)
    a = reqDB.getAll()
    assert(len(a)==2)
    assert(a[1].amount == 2000)
    assert(reqDB.existRequestID(3)==False)
    assert(reqDB.existRequestID(1)==True)
    request1 = reqDB.getByRequestID(1)
    request2 = reqDB.getByRequestID(3)
    assert(request1.amount == 3000)
    assert(request2 == False)
    print('Passed Discount test')

def ClientMeetingTest(db):
    cm = ClientMeeting(1,'10/10/2015','test')
    assert(cm.clientID == 1)
    assert(len(cm.getAll()) ==3)
    assert(equal_tuples(cm.getAll(),(1,'10/10/2015','test')))
    cm.setAll((12,'12/10/2015','te2st'))
    assert(equal_tuples(cm.getAll(), (12,'12/10/2015','te2st')))
    assert (db.isConnectionOk() == 1)
    db.executeDoQuery("DROP TABLE IF EXISTS clientMeeting")
    db.executeDoQuery(
        "CREATE TABLE IF NOT EXISTS clientMeeting(clientID integer,date text,comment text,FOREIGN KEY(clientid) REFERENCES client(id))")
    reqDB = ClientMeetingDBInterface(db)
    meeting = ClientMeeting(1,'20/10/2015','a meeting')
    reqDB.add(meeting)
    meeting = reqDB.get(meeting)
    assert(meeting.clientID==1)
    meeting.date= '10/10/2015'
    reqDB.update(meeting)
    meeting = reqDB.get(meeting)
    assert(meeting.date=='10/10/2015')
    temp = ClientMeeting(1,'22/10/2015','a meeting')
    reqDB.add(temp)
    a = reqDB.getAll()
    assert(len(a)==2)
    assert(a[1].date =='22/10/2015')
    print('Passed ClientMeeting test')

def TaskTest(db):
    t = Task(1,1,'test','op',TaskPriority.Invalid.value,'10/10/2015',TaskStatus.Pending.value,'')
    assert(t.id == 1)
    assert(len(t.getAll()) ==8)
    assert(equal_tuples(t.getAll(),(1,1,'test','op',TaskPriority.Invalid.value,'10/10/2015',TaskStatus.Pending.value,'')))
    t.setAll((12,12,'te2st','o2p',TaskPriority.High.value,'10/12/2015',TaskStatus.Invalid.value,'1'))
    assert(equal_tuples(t.getAll(), (12,12,'te2st','o2p',TaskPriority.High.value,'10/12/2015',TaskStatus.Invalid.value,'1')))
    assert (db.isConnectionOk() == 1)
    db.executeDoQuery("DROP TABLE IF EXISTS task")
    db.executeDoQuery(
        "CREATE TABLE IF NOT EXISTS task(id INTEGER PRIMARY KEY AUTOINCREMENT, requestID integer,description text,operator text,priority integer,deadline text,status integer,comment text,FOREIGN KEY(requestID) references request(id),FOREIGN KEY(operator) references account(email))")
    reqDB = TaskDBInterface(db)
    task = Task(0,1,'just cook','sarah@sep.se',TaskPriority.High.value,'20/10/2015',TaskStatus.Pending.value,'no comments!')
    task.id = reqDB.add(task)
    task = reqDB.get(task)
    assert(task.deadline=='20/10/2015')
    task.deadline= '10/10/2015'
    reqDB.update(task)
    task = reqDB.get(task)
    assert(task.deadline=='10/10/2015')
    temp = Task(0,1,'just clean','sarah@sep.se',TaskPriority.High.value,'21/10/2015',TaskStatus.Pending.value,'no comments!')
    temp.id=reqDB.add(temp)
    a = reqDB.getAll()
    assert(len(a)==2)
    assert(a[1].deadline =='21/10/2015')
    a = reqDB.getByID(1)
    assert(a.deadline =='10/10/2015')
    a = reqDB.getByRequestID(1)
    assert(len(a)==2)
    assert(a[0].deadline == '10/10/2015')
    assert(a[1].deadline == '21/10/2015')
    a = reqDB.getByStatus(TaskStatus.Pending.value)
    assert(len(a)==2)
    assert(a[0].deadline == '10/10/2015')
    assert(a[1].deadline == '21/10/2015')
    a = reqDB.getByStatusAndEmail(TaskStatus.Pending.value,'sarah@sep.se')
    assert(len(a)==2)
    assert(a[0].deadline == '10/10/2015')
    a = reqDB.getByStatusAndEmail(TaskStatus.Pending.value,'test@sep.se')
    assert(a == False)
    a = reqDB.getByTaskID(1)
    assert(a.deadline =='10/10/2015')
    a = reqDB.getTasksByAccTypeUser("User",'sarah@sep.se')
    assert(len(a)==2)
    assert(a[0].deadline == '10/10/2015')
    assert(a[1].deadline == '21/10/2015')
    a = reqDB.getTasksByAccTypeUser("Manager",'sarah@sep.se')
    assert(len(a)==2)
    assert(a[0].deadline == '10/10/2015')
    assert(a[1].deadline == '21/10/2015')
    print('Passed Task test')

def ScheduleTest(db):
    s = Schedule(1,'test',10,12,'10/10/2015')
    assert(s.id == 1)
    assert(len(s.getAll()) ==5)
    assert(equal_tuples(s.getAll(),(1,'test',10,12,'10/10/2015')))
    s.setAll((12,'te2st',12,13,'10/13/2015'))
    assert(equal_tuples(s.getAll(), (12,'te2st',12,13,'10/13/2015')))
    assert (db.isConnectionOk() == 1)
    db.executeDoQuery("DROP TABLE IF EXISTS schedule")
    db.executeDoQuery(
        "CREATE TABLE IF NOT EXISTS schedule(id INTEGER PRIMARY KEY AUTOINCREMENT,employee text,startHour integer,endHour integer,date text,FOREIGN KEY(employee) REFERENCES account(email))")
    reqDB = ScheduleDBInterface(db)
    schedule = Schedule(0,'sarah@sep.se',10,20,'20/10/2015')
    schedule.id=reqDB.add(schedule)
    schedule = reqDB.get(schedule)
    assert(schedule.employee=='sarah@sep.se')
    schedule.date= '10/10/2015'
    reqDB.update(schedule)
    schedule = reqDB.get(schedule)
    assert(schedule.date=='10/10/2015')
    temp = Schedule(0,'sarah@sep.se',10,20,'22/10/2015')
    temp.id=reqDB.add(temp)
    a = reqDB.getAll()
    assert(len(a)==2)
    assert(a[1].date =='22/10/2015')
    print('Passed Schedule test')

def ModelTests(connection_name):
    GenericMethodsTest()
    DBTest()
    db = DBConnectionSQLite(connection_name)
    AccountTest(db)
    ClientTest(db)
    RequestTest(db)
    FinancialRequestTest(db)
    RecruitmentRequestTest(db)
    RequestDetailsTest(db)
    DiscountTest(db)
    ClientTest(db)
    TaskTest(db)
    ScheduleTest(db)
    ClientMeetingTest(db)
    os.remove('test_connection.test')
    assert(os.path.isfile('test_connection.test')==False)










